---

spring :
 datasource :
  url : jdbc:mysql://localhost:3306/pmysql
  username : root
  password : root
 jpa :
  hibernate :
   ddl-auto : update
  show-sql : true
  properties :
   hibernate :
    format_sql : true 
  
server :
 port : 8080
   

 